---
title: "Sumitra Ghalley"
subtitle: "Student MBA Portfolio — One Page"
date: "2025-10-25"
format: html
---

## About
My background is in media and marketing. My career started as marketing officer with enhacing hands-on experience on branding, plan campaign, and customer engagement. Currently through pursuing MBA, I am exploring to creative marketing insights with analytical and strategic decision making to support business growth and innovation.

## Education
*Master of Business Administration (MBA)* — University Canada West, Vancouver, BC (2024–2026)  
- Focus: Digital Marketing, Leadership, Finance, Business Analytics  

*B.A. in Media Studies* — Royal University of Bhutan, Bhutan (2018–2021)  
- Coursework: Information Design, Visual Art, Communication  

## Experience
*Sales Associate* — Burnaby, BC (Present)  
- Provide customers services such as greeting, identify their needs and provide reccommendation.   
- Ensure the store presentation such as arranging shelves.
- Inventory management.

*Marketing Officer* — Sherza Allstore, Bhutan (2024)  
- Made plans to executed marketing campaigns to boost brand awareness and sales.   
- Managed and created social media and digital contents to build consumers engagement.
- Ensured consistency in brand messaging by collabrating with cross-functional teams.  

*Intern as Communications Assistant* — Bhutan Boardcasting Services, Thailand (2020–2021)  
- Assisted to create  and develop contents for digital platforms such as emails, social media, and company websites.  
- Assisted to create presentations and reports for the team.
- Perform clerical duties. 

## Skills
- *Marketing Strategy :* Content Creation, branding and communication   
- *Leadership:* Team supervise, Problem-Solving   
- *Research & Analytical Skills:* verify facts, analyse media trends.  
- *Languages:* English, Dzongkha, Nepali, Hindi

## Contact
sumitraghalley1@gmail.com  
Vancouver, BC
